AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  LineChannelAccessToken:
    Type: String
    Description: "LINE のアクセストークン"
  LineChannelSecret:
    Type: String
    Description: "LINE のチャンネルシークレット"
  StatemachineArn:
    Type: String
    Description: "sfn arn"
  S3BucktName:
   Type: String
   Description: "S3バケット の名前"
#  CustomLabelProjectArn:
#    Type: String
#    Description: "カスタムラベルのプロジェクトネーム"
#  VersionName:
#    Type: String
#    Description: "モデルのバージョン名"
#  DynamoDBTableName:
#    Type: String
#    Description: "DynamoDBのテーブル名"
Resources:
  CallStepFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      CodeUri: functions/CallSFN/
      Handler: callsfn.lambda_handler
      Environment:
        Variables:
          LINE_CHANNEL_ACCESS_TOKEN:
            Ref: LineChannelAccessToken
          LINE_CHANNEL_SECRET:
            Ref: LineChannelSecret
          STATEMACHINE_ARN:
            Ref: StatemachineArn
      Events:
        API:
          Type: Api
          Properties:
            Path: /api_endpoint
            Method: post
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt S3RekognitionDBStateMachine.Name
    Metadata:
      SamResourceId: CallStepFunction

  LineS3Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      CodeUri: functions/LINEImageS3/
      Handler: lineimages3.lambda_handler
      Environment:
        Variables:
          LINE_CHANNEL_ACCESS_TOKEN:
            Ref: LineChannelAccessToken
          LINE_CHANNEL_SECRET:
            Ref: LineChannelSecret
      Policies:
        - S3WritePolicy:
          BucketName: 
            Ref: S3BucktName
    Metadata:
      SamResourceId: LineS3Function

  S3RekognitionDBStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/sfn.asl.json
      DefinitionSubstitutions:
         LineS3Function: !GetAtt LineS3Function.Arn
      Policies:
        LambdaInvokePolicy:
          FunctionName: !Ref LineS3Function
  LineImageS3Bucket:
    Type : AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: S3BucktName


#  FishDynamoDB:
#    Type: AWS::Serverless::SimpleTable
#    Properties:
#      TableName:
#        Ref: DynamoDBTableName
#      PrimaryKey:
#        Name: FishName
#        Type: String
Outputs:
  ApiEndpointURL:
    Description: API Endpoint URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApi.Stage}/api_endpoint